name: order
version: 0.3.2
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: An example from boarding.
homepage: https://github.com/dzenanr/boarding
environment:
  sdk: '>=1.10.0 <2.0.0'
documentation: http://goo.gl/kXlDOJ
dependencies:
  browser: ^0.10.0+2 
  boarding: ^0.3.2
transformers:
- $dart2js:
    minify: true
    terse: true
